version: '3.8'

services:
  riscv-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app  # Monta el código de la API para desarrollo en vivo