FROM python:3.9-slim

WORKDIR /app

# Copiamos e instalamos las dependencias primero para aprovechar el cache de Docker
COPY ./api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el resto del código de la API
COPY ./api /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8070"]