import json
import os

# --- Helpers ---
def bool_to_cpp(b):
    """Converts Python bool to C++ bool string."""
    return "true" if b else "false"

def bool_to_dart(b):
    """Converts Python bool to Dart bool string."""
    return "true" if b else "false"

def calculate_control_word(instruction, layout):
    """Calculates the 16-bit control word for a given instruction."""
    word = 0
    # The names of the fields in the layout that constitute the control word
    control_fields = layout['fields'].keys()
    
    for name in control_fields:
        details = layout['fields'][name]
        pos = details['position']
        width = details['width']
        
        # Get value from the instruction dictionary
        val = instruction.get(name)
        
        if val is None:
            continue

        # Handle boolean values
        if isinstance(val, bool):
            val = 1 if val else 0
        
        # Handle the -1 case for "don't care" / all-ones
        if val == -1:
            val = (1 << width) - 1
            
        masked_val = val & ((1 << width) - 1)
        word |= (masked_val << pos)
        
    return word

# --- Generators ---
def generate_cpp_header(instructions, layout, path):
    """Generates the C++ header file with the control table data."""
    with open(path, 'w', encoding='utf-8') as f:
        f.write("// Generated file. DO NOT EDIT.\n")
        f.write("// This file is automatically generated by the 'generate_control_table.py' script.\n")
        f.write("// Any changes made to this file will be overwritten.\n\n")
        f.write('#pragma once\n\n')
        f.write('#include "ControlUnit.h" // Defines InstructionInfo\n')
        f.write('#include <cstdint>\n')
        f.write('#include <vector>\n\n')
        f.write("namespace riscv_sim {\n\n")

        # --- Control Word Layout ---
        f.write("/*\n * Control Word Layout\n")
        f.write(" * ---------------------\n")
        f.write(f" * {layout['comment']}\n")
        f.write(" */\n")
        f.write("namespace ControlWord {\n")
        for name, details in layout['fields'].items():
            f.write(f"    // {details['description']}\n")
            f.write(f"    constexpr int {name}_pos = {details['position']};\n")
            f.write(f"    constexpr int {name}_width = {details['width']};\n")
        f.write("} // namespace ControlWord\n\n")

        # --- Instruction Table ---
        f.write("// Fields: instr, PCsrc, BRwr, ALUsrc, ALUctr, MemWr, ResSrc, ImmSrc, mask, value, type, cycles, control_word\n")
        f.write("static const InstructionInfo control_table_data[] = {\n")
        for item in instructions:
            # Handle -1 for unsigned types by casting, which wraps them to 255 (0xFF)
            alu_ctr_val = f'static_cast<uint8_t>({item["ALUctr"]})'
            res_src_val = f'static_cast<uint8_t>({item["ResSrc"]})'
            imm_src_val = f'static_cast<uint8_t>({item["ImmSrc"]})'

            line = (
                f'    {{"{item["instr"]}", {item["PCsrc"]}, {bool_to_cpp(item["BRwr"])}, '
                f'{item["ALUsrc"]}, {alu_ctr_val}, {bool_to_cpp(item["MemWr"])}, '
                f'{res_src_val}, {imm_src_val}, 0x{item["mask"]:X}, '
                f'0x{item["value"]:X}, \'{item["type"]}\', {item["cycles"]}, 0x{item["control_word"]:04X}}},\n'
            )
            f.write(line)
        f.write("};\n\n")
        f.write("} // namespace riscv_sim\n")
    print(f"Generated C++ header: {path}")

def generate_dart_file(instructions, layout, path):
    """Generates the Dart file with the control table data."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write("// Generated file. DO NOT EDIT.\n")
        f.write("// This file is automatically generated by the 'generate_control_table.py' script.\n")
        f.write("// Any changes made to this file will be overwritten.\n\n")

        # --- Control Word Layout ---
        f.write("class ControlWordField {\n")
        f.write("  final String name;\n")
        f.write("  final int position;\n")
        f.write("  final int width;\n")
        f.write("  final String description;\n\n")
        f.write("  const ControlWordField({\n")
        f.write("    required this.name, required this.position, required this.width, required this.description,\n")
        f.write("  });\n}\n\n")
        f.write("const Map<String, ControlWordField> controlWordLayout = {\n")
        for name, details in layout['fields'].items():
            f.write(f'  "{name}": const ControlWordField(\n')
            f.write(f'    name: "{name}",\n')
            f.write(f'    position: {details["position"]},\n')
            f.write(f'    width: {details["width"]},\n')
            f.write(f'    description: "{details["description"]}",\n')
            f.write("  ),\n")
        f.write("};\n\n")

        # --- Instruction Table ---
        f.write("class InstructionInfo {\n")
        f.write("  final String instr;\n")
        f.write("  final int pcSrc;\n")
        f.write("  final bool brWr;\n")
        f.write("  final int aluSrc;\n")
        f.write("  final int aluCtr;\n")
        f.write("  final bool memWr;\n")
        f.write("  final int resSrc;\n")
        f.write("  final int immSrc;\n")
        f.write("  final int mask;\n")
        f.write("  final int value;\n")
        f.write("  final String type;\n")
        f.write("  final int cycles;\n\n")
        f.write("  final int controlWord;\n\n")
        f.write("  const InstructionInfo({\n")
        f.write("    required this.instr, required this.pcSrc, required this.brWr, required this.aluSrc,\n")
        f.write("    required this.aluCtr, required this.memWr, required this.resSrc, required this.immSrc,\n")
        f.write("    required this.mask, required this.value, required this.type, required this.cycles, required this.controlWord,\n")
        f.write("  });\n}\n\n")
        f.write("const List<InstructionInfo> controlTable = [\n")
        for item in instructions:
            f.write("  InstructionInfo(\n")
            f.write(f'    instr: "{item["instr"]}",\n')
            f.write(f'    pcSrc: {item["PCsrc"]},\n')
            f.write(f'    brWr: {bool_to_dart(item["BRwr"])},\n')
            f.write(f'    aluSrc: {item["ALUsrc"]},\n')
            f.write(f'    aluCtr: {item["ALUctr"]},\n')
            f.write(f'    memWr: {bool_to_dart(item["MemWr"])},\n')
            f.write(f'    resSrc: {item["ResSrc"]},\n')
            f.write(f'    immSrc: {item["ImmSrc"]},\n')
            f.write(f'    mask: 0x{item["mask"]:X},\n')
            f.write(f'    value: 0x{item["value"]:X},\n')
            f.write(f'    type: \'{item["type"]}\',\n')
            f.write(f'    cycles: {item["cycles"]},\n')
            f.write(f'    controlWord: 0x{item["control_word"]:04X},\n')
            f.write("  ),\n")
        f.write("];\n")
    print(f"Generated Dart file: {path}")

def generate_python_file(instructions, layout, path):
    """Generates the Python file with the control table data."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write("# Generated file. DO NOT EDIT.\n")
        f.write("# This file is automatically generated by the 'generate_control_table.py' script.\n")
        f.write("# Any changes made to this file will be overwritten.\n\n")

        # --- Control Word Layout ---
        f.write("CONTROL_WORD_LAYOUT = ")
        f.write(json.dumps(layout, indent=4))
        f.write("\n\n")

        f.write("CONTROL_TABLE = [\n")
        for item in instructions:
            f.write(f"    {repr(item)},\n")
        f.write("]\n")
    print(f"Generated Python file: {path}")

def main():
    """Main function to generate all source files."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    json_path = os.path.join(script_dir, 'instructions.json')

    with open(json_path, 'r', encoding='utf-8') as f:
        json_data = json.load(f)
        instructions = json_data["instructions"]
        control_word_layout = json_data["control_word_layout"]

    for item in instructions:
        item['control_word'] = calculate_control_word(item, control_word_layout)

    generate_cpp_header(instructions, control_word_layout, os.path.join(project_root, 'core', 'include', 'ControlTableData.h'))
    generate_dart_file(instructions, control_word_layout, os.path.join(project_root, 'simulator_ui', 'lib', 'generated', 'control_table.g.dart'))
    generate_python_file(instructions, control_word_layout, os.path.join(project_root, 'api', 'src', 'control_table_data.py'))

    print("\nSource files generated successfully.")
    print("Please recompile your projects to apply the changes.")

if __name__ == "__main__":
    main()