# Generated file. DO NOT EDIT.
# This file is automatically generated by the 'generate_control_table.py' script.
# Any changes made to this file will be overwritten.

CONTROL_WORD_LAYOUT = {
    "comment": "Define la posici\u00f3n de los bits para cada se\u00f1al de control en la palabra de control. Esto es para documentaci\u00f3n y para un uso futuro en la generaci\u00f3n de la l\u00f3gica de control.",
    "fields": {
        "MemWr": {
            "position": 2,
            "width": 1,
            "description": "Escritura en la memoria de datos"
        },
        "BRwr": {
            "position": 3,
            "width": 1,
            "description": "Escritura en el banco de registros"
        },
        "ALUsrc": {
            "position": 4,
            "width": 1,
            "description": "Selector de fuente para la ALU (Registro vs Inmediato)"
        },
        "PCsrc": {
            "position": 6,
            "width": 2,
            "description": "Selector de fuente para el PC (PC+4, ALU, etc.)"
        },
        "ImmSrc": {
            "position": 8,
            "width": 3,
            "description": "Selector de fuente del inmediato"
        },
        "ResSrc": {
            "position": 11,
            "width": 2,
            "description": "Fuente del resultado para la escritura en registro (ALU vs Mem)"
        },
        "ALUctr": {
            "position": 13,
            "width": 3,
            "description": "Se\u00f1al de control de la ALU"
        }
    }
}

CONTROL_TABLE = [
    {'instr': 'add', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 1, 'ALUctr': 0, 'MemWr': False, 'ResSrc': 1, 'ImmSrc': -1, 'mask': 4261412991, 'value': 51, 'type': 'R', 'cycles': 4, 'control_word': 3864},
    {'instr': 'sub', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 1, 'ALUctr': 1, 'MemWr': False, 'ResSrc': 1, 'ImmSrc': -1, 'mask': 4261412991, 'value': 1073741875, 'type': 'R', 'cycles': 4, 'control_word': 12056},
    {'instr': 'and', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 1, 'ALUctr': 2, 'MemWr': False, 'ResSrc': 1, 'ImmSrc': -1, 'mask': 4261412991, 'value': 28723, 'type': 'R', 'cycles': 4, 'control_word': 20248},
    {'instr': 'or', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 1, 'ALUctr': 3, 'MemWr': False, 'ResSrc': 1, 'ImmSrc': -1, 'mask': 4261412991, 'value': 24627, 'type': 'R', 'cycles': 4, 'control_word': 28440},
    {'instr': 'addi', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 0, 'ALUctr': 0, 'MemWr': False, 'ResSrc': 1, 'ImmSrc': 0, 'mask': 28799, 'value': 19, 'type': 'I', 'cycles': 4, 'control_word': 2056},
    {'instr': 'lw', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 0, 'ALUctr': 0, 'MemWr': False, 'ResSrc': 0, 'ImmSrc': 0, 'mask': 28799, 'value': 8195, 'type': 'I', 'cycles': 5, 'control_word': 8},
    {'instr': 'sw', 'PCsrc': 0, 'BRwr': False, 'ALUsrc': 0, 'ALUctr': 0, 'MemWr': True, 'ResSrc': -1, 'ImmSrc': 1, 'mask': 28799, 'value': 8227, 'type': 'S', 'cycles': 4, 'control_word': 6404},
    {'instr': 'beq', 'PCsrc': 1, 'BRwr': False, 'ALUsrc': 1, 'ALUctr': 1, 'MemWr': False, 'ResSrc': -1, 'ImmSrc': 2, 'mask': 28799, 'value': 99, 'type': 'B', 'cycles': 3, 'control_word': 14928},
    {'instr': 'bne', 'PCsrc': 1, 'BRwr': False, 'ALUsrc': 1, 'ALUctr': 1, 'MemWr': False, 'ResSrc': -1, 'ImmSrc': 2, 'mask': 28799, 'value': 4195, 'type': 'B', 'cycles': 3, 'control_word': 14928},
    {'instr': 'jal', 'PCsrc': 1, 'BRwr': True, 'ALUsrc': -1, 'ALUctr': -1, 'MemWr': False, 'ResSrc': 2, 'ImmSrc': 3, 'mask': 127, 'value': 111, 'type': 'J', 'cycles': 4, 'control_word': 62296},
    {'instr': 'sll', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 1, 'ALUctr': 6, 'MemWr': False, 'ResSrc': 1, 'ImmSrc': -1, 'mask': 4261412991, 'value': 4147, 'type': 'R', 'cycles': 4, 'control_word': 53016},
    {'instr': 'ori', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 0, 'ALUctr': 3, 'MemWr': False, 'ResSrc': 1, 'ImmSrc': 0, 'mask': 28799, 'value': 24595, 'type': 'I', 'cycles': 4, 'control_word': 26632},
    {'instr': 'lui', 'PCsrc': 0, 'BRwr': True, 'ALUsrc': 0, 'ALUctr': 0, 'MemWr': False, 'ResSrc': 1, 'ImmSrc': 4, 'mask': 127, 'value': 55, 'type': 'U', 'cycles': 4, 'control_word': 3080},
]
